language: node_js
node_js:
  - "0.10"
  - "0.8"

# Make sure we have new NPM.
before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8"  ] || npm install -g npm@1.4.28'
  - npm install -g npm
  - npm config set loglevel warn

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli

script:
  - grunt
